### ISSUE TITLE
eae mano...

### ISSUE THREAD

**Issue by phm-aguiar** [ArthurSobreira/42_fdf#1]
tava testando essa praga e ta toda bugada ... espero que concerte, também espero que voce refatore todo o seu código linha por linha, por favor, está muito bugado, tá muito lerdo e pouco funcional, espero que melhore, abraços!! 

'='

**Comment by phm-aguiar** [comment]
quando sera que vai sair a feature arrumando isso?

**Comment by ArthurSobreira** [comment]
nunca

**Comment by phm-aguiar** [comment]
olha o cara mano
